---
settings:
  name: StorageGRID
  search: storagegrid-enable,storagegrid,storagegrid-appliances
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: false
    harmony_enabled: false
  langs: pt-br,us-en,de-de,es-es,fr-fr,it-it,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documentação do produto StorageGRID
    url: "/index.html"
